version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - jacanales
  assignees:
  - jacanales
 # Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - jacanales
  assignees:
  - jacanales

