pull_request_rules:
  - name: Automatic merge on dependabot requests
    conditions:
      - "author=dependabot[bot]"
      - "base=main"
      - check-success=Build and test
    actions:
      merge:
        method: merge
  - name: Automatic merge on mergify requests
    conditions:
      - "base=main"
      - "head~=^mergify/"
      - check-success=Build and test
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
