name: Check NPM Modules
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1.8.37
      - run: yarn build